#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091,SC2154,SC2164

# docker-skies-adsb is a wrapper around skies-adsb, which is used under the MIT license. 
# See https://github.com/machineinteractive/skies-adsb and
# https://github.com/machineinteractive/skies-adsb/LICENSE for 
#---------------------------------------------------------------------------------------------
# As it pertains to this docker container wrapper only:
# Copyright (C) 2025, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

source /scripts/common

"${s6wrap[@]}" echo "[INFO] Started as an s6 service"

cd /skies-adsb
exec ./use_existing_adsb.sh